<?php
        ob_start();
		if($_GET['page']=="lapbm"){
        include('assets/laporan/lapbm/report.php');
		}
		if($_GET['page']=="laporder"){
        include('assets/laporan/laporder/report.php');
		}
		if($_GET['page']=="laptransit"){
        include('assets/laporan/laptransit/report.php');
		}
		if($_GET['page']=="laprelok"){
        include('assets/laporan/laprelok/report.php');
		}
		if($_GET['page']=="lapso"){
        include('assets/laporan/lapsalesorder/report.php');
		}
		if($_GET['page']=="lapretpenj"){
        include('assets/laporan/lapretpenj/report.php');
		}
		if($_GET['page']=="lapbiret"){
        include('assets/laporan/lapbiret/report.php');
		}
		if($_GET['page']=="lapbisup"){
        include('assets/laporan/lapbisup/report.php');
		}
		if($_GET['page']=="lapbibong"){
        include('assets/laporan/lapbibong/report.php');
		}
		if($_GET['page']=="lappen"){
        include('assets/laporan/lappenjualan/report.php');
		}
		if($_GET['page']=="lappennon"){
        include('assets/laporan/lappenjualannon/report.php');
		}
		if($_GET['page']=="lappenpel"){
        include('assets/laporan/lappenpel/report.php');
		}
		if($_GET['page']=="laptkbm"){
        include('assets/laporan/laptkbm/report.php');
		}
		if($_GET['page']=="laptkbmj"){
        include('assets/laporan/laptkbmj/report.php');
		}
		if($_GET['page']=="lapperaset"){
        include('assets/laporan/lapperaset/report.php');
		}
		if($_GET['page']=="lapsiapaset"){
        include('assets/laporan/lapsiapaset/report.php');
		}
		if($_GET['page']=="lappengaset"){
        include('assets/laporan/lappengaset/report.php');
		}
		if($_GET['page']=="lapmainaset"){
        include('assets/laporan/lapmainaset/report.php');
		}
		if($_GET['page']=="laphapusaset"){
        include('assets/laporan/laphapusaset/report.php');
		}
		if($_GET['page']=="slip" and $_GET['jenis']==1){
        include('assets/hrm/slip/report.php');
		}
		if($_GET['page']=="sliphabor"){
        include('assets/hrm/sliphabor/report.php');
		}
		if($_GET['page']=="cetakspj" and $_GET['jenis']=="0"){
        include('assets/inventory/cetakspjpen/report.php');
		}else
		if($_GET['page']=="cetakspj" and $_GET['jenis']=="1"){
        include('assets/inventory/cetakspjpen/report2.php');
		}
		if($_GET['page']=="cetakspj" and $_GET['jenis']=="2"){
        include('assets/inventory/kirimda/report2.php');
		}
		if($_GET['page']=="cetakspjriject" and $_GET['jenis']=="1"){
        include('assets/inventory/jualriject/report2.php');
		}
		if($_GET['page']=="cetakspj2"){
        include('assets/inventory/cetakspjpen/report_fak.php');
		}
		if($_GET['page']=="returpen"){
        include('assets/inventory/retur_jual/report.php');
		}
		if($_GET['page']=="retur"){
        include('assets/inventory/retur/report.php');
		}
		if($_GET['page']=="penjualan"){
        include('assets/inventory/penjualan/report.php');
		}
		if($_GET['page']=="brg_masuk_transit"){
        include('assets/inventory/brg_masuk_transit/report.php');
		}
		if($_GET['page']=="brg_masuk_non"){
        include('assets/inventory/brg_masuk_non/report.php');
		}
		if($_GET['page']=="txex"){
        include('assets/inventory/tx_expediture/report.php');
		}
		if($_GET['page']=="bukta"){
        include('assets/inventory/buku_tagihan/report.php');
		}
		if($_GET['page']=="order"){
        include('assets/inventory/order/report.php');
		}
		if($_GET['page']=="brgkeluar"){
        include('assets/inventory/brgkeluar/report.php');
		}
		if($_GET['page']=="brgmasuk"){
        include('assets/inventory/brg_masuk/report.php');
		}
		if($_GET['page']=="pgnbrng"){
        include('assets/inventory/pgnbrng/report.php');
		}
		if($_GET['page']=="cetakbiayapem"){
        include('assets/inventory/brg_masuk/report2.php');
		}
		if($_GET['page']=="prp"){
        include('assets/inventory/prp/report.php');
		}
		if($_GET['page']=="biling"){
        include('assets/inventory/billing/report.php');
		}
		if($_GET['page']=="order-pemb"){
        include('assets/inventory/order_pemb/report.php');
		}
		if($_GET['page']=="transit"){
        include('assets/inventory/transit/report.php');
		}
		if($_GET['page']=="korpi" and $_GET['jenis']==1){
        include('assets/inventory/koresipiutang/report.php');
		}
		if($_GET['page']=="korpi" and $_GET['jenis']==2){
        include('assets/inventory/koresipiutang/report2.php');
		}
		if($_GET['page']=="korpi" and $_GET['jenis']==3){
        include('assets/inventory/koresipiutang/report3.php');
		}
		if($_GET['page']=="salesorder"){
        include('assets/inventory/salesorder/report.php');
		}
		if($_GET['page']=="jualriject"){
        include('assets/inventory/jualriject/report.php');
		}
		if($_GET['page']=="po"){
        include('assets/inventory/po/report.php');
		}
		if($_GET['page']=="tagkem"){
        include('assets/inventory/tagihan_kembali/report.php');
		}
		if($_GET['page']=="tkbmbeli"){
        include('assets/inventory/tkbmbeli/report.php');
		}
		if($_GET['page']=="tkbmjual"){
        include('assets/inventory/tkbmjual/report.php');
		}
		if($_GET['page']=="appbt"){
        include('assets/inventory/app_bt/report.php');
		}
		if($_GET['page']=="ordernon"){
        include('assets/inventory/orderpemn/report.php');
		}
		if($_GET['page']=="bonus"){
        include('assets/hrm/bonus/report.php');
		}
        if($_GET['page']=="appjual"){
        include('assets/inventory/appjual/report.php');
		}
		if($_GET['page']=="pengbum"){
        include('assets/inventory/pengbum/report.php');
		}
		if($_GET['page']=="order_pemb"){
        include('assets/inventory/order_pemb/report.php');
		}
		if($_GET['page']=="ordexp"){
        include('assets/inventory/ordexp/report.php');
		}
		if($_GET['page']=="v_kasmasuk"){
        include('assets/akutansi/kasmasuk/voucher.php');
		}
		if($_GET['page']=="v_kaskeluar"){
        include('assets/akutansi/kas_keluar/voucher.php');
		}
		if($_GET['page']=="v_bankkeluar"){
        include('assets/akutansi/bank_keluar/voucher.php');
		}
		if($_GET['page']=="v_bankmasuk"){
        include('assets/akutansi/bank_masuk/voucher.php');
		}
		if($_GET['page']=="v_jurum"){
        include('assets/akutansi/jurnal_umum/voucher.php');
		}
		if($_GET['page']=="v_htnonpo"){
        include('assets/akutansi/hutang_nonpo/voucher.php');
		}
		if($_GET['page']=="lapkasbank"){
        include('assets/laporan/lapkasbank/report.php');
		}
		if($_GET['page']=="lappenbar"){
        include('assets/laporan/lappenbarang/report.php');
		}
		if($_GET['page']=="lapsumpenbar"){
        include('assets/laporan/lapsumpenbarang/report.php');
		}
		if($_GET['page']=="lappendtl"){
        include('assets/laporan/lappendtl/report.php');
		}
		if($_GET['page']=="laprekappo"){
        include('assets/laporan/laprekappo/report.php');
		}
		if($_GET['page']=="lapposupp"){
        include('assets/laporan/lapposupp/report.php');
		}
		if($_GET['page']=="lapposemnon"){
        include('assets/laporan/lapposemnon/report.php');
		}
		if($_GET['page']=="lapexp"){
        include('assets/laporan/lapexp/report.php');
		}
		if($_GET['page']=="lappoin"){
        include('assets/laporan/lappoin/report.php');
		}

		$content = ob_get_clean();
        require_once('assets/plugin/html2pdf/html2pdf.class.php');
        try
        {
            $html2pdf = new HTML2PDF('P', 'A4', 'en');
            $html2pdf->setTestTdInOnePage(false);
            $html2pdf->writeHTML($content, isset($_GET['vuehtml']));
            $html2pdf->Output('report.pdf');
        }
        catch(HTML2PDF_exception $e) {
            echo $e;
            exit;
        }
    ?>
